import { writeFile } from "node:fs/promises";
import { db, firmwareTable, vulnerabilitiesTable, aiReportsTable, scanResultsTable } from "@workspace/db";
import { eq } from "drizzle-orm";
import { reportPath } from "../lib/paths.js";

export async function generateTextReport(firmwareId: number): Promise<{ path: string; size: number }> {
  const [fw] = await db.select().from(firmwareTable).where(eq(firmwareTable.id, firmwareId));
  const vulns = await db.select().from(vulnerabilitiesTable).where(eq(vulnerabilitiesTable.firmwareId, firmwareId));
  const [report] = await db.select().from(aiReportsTable).where(eq(aiReportsTable.firmwareId, firmwareId));
  const [scan] = await db.select().from(scanResultsTable).where(eq(scanResultsTable.firmwareId, firmwareId));

  const lines = [
    "=".repeat(60),
    "VIV SCANNER — FIRMWARE SECURITY REPORT",
    "=".repeat(60),
    "",
    `Firmware: ${fw?.name ?? "Unknown"}`,
    `Architecture: ${fw?.architecture ?? "Unknown"}`,
    `Scan Date: ${scan?.startedAt?.toISOString() ?? new Date().toISOString()}`,
    `Risk Level: ${scan?.riskLevel?.toUpperCase() ?? "UNKNOWN"}`,
    `Vulnerabilities Found: ${vulns.length}`,
    "",
    "-".repeat(60),
    "EXECUTIVE SUMMARY (AI — Google Gemini 2.5 Flash)",
    "-".repeat(60),
    report?.summary ?? "No AI summary available.",
    "",
    "-".repeat(60),
    "KEY FINDINGS",
    "-".repeat(60),
    ...(report ? JSON.parse(report.keyFindings) as string[] : []).map((f, i) => `${i + 1}. ${f}`),
    "",
    "-".repeat(60),
    "RECOMMENDATIONS",
    "-".repeat(60),
    ...(report ? JSON.parse(report.recommendations) as string[] : []).map((r, i) => `${i + 1}. ${r}`),
    "",
    "-".repeat(60),
    "VULNERABILITIES",
    "-".repeat(60),
    ...vulns.map((v) => `[${v.severity.toUpperCase()}] ${v.type}\n  File: ${v.affectedFile}\n  ${v.description}\n  Fix: ${v.recommendation}\n`),
    "",
    "=".repeat(60),
    "Generated by Viv Scanner",
    "=".repeat(60),
  ];

  const outPath = reportPath(firmwareId);
  const content = lines.join("\n");
  await writeFile(outPath, content, "utf8");

  return { path: outPath, size: Buffer.byteLength(content) };
}
